### PR TITLE
fix dllname for posix systems

### PR DESCRIPTION
**Pull request by pmp-p**
hi, only tested on wasm so far https://pygame-web.github.io/showroom/raylib/

### CODE REVIEW

**Comment by sDos280** [comment]
firstly, thanks for the submission 😃, but unfortunately I will not add any Linux/Mac/wasm support until I have a copy of the dynamic libraries of raylib for those OS(s). fill free to add yours and then I will accept the PR.

secondly, does it really work for wasm? the link that you sent (https://pygame-web.github.io/showroom/raylib/) seems to work well. I will be so happy if you will be if you will make an in-depth explanation of how you did that, feel free to open a discussion/issue on how you did that... 

thanks 👍💖.

**Comment by pmp-p** [comment]
i don't have linux/mac .so build and they would not be very portable anyway. But i can provide the wasm one if you want it was built with  :
```TARGET=/data/git/pygbag-samples/raylibtest/raypyc/libraylib.so
emcmake cmake ../raylib-4.2.0 -DCMAKE_INSTALL_PREFIX=/opt/python-wasm-sdk/devices/emsdk/usr -DPLATFORM=Web -DWITH_PIC=on -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=NO
emmake make
emcc -shared -o $TARGET ./raylib/libraylib.a
```

and help of https://github.com/pygame-web/python-wasm-sdk

all i did was just remove the `emscripten_sleep(16)` from raylib 4.2.0 release.

**Comment by sDos280** [comment]
ok 👍. thank you very much.

**Comment by pmp-p** [comment]
for multiple libraries support it would problably need something like `import sysconfig; sysconfig.get_config_var('HOST_GNU_TYPE')` to sort lib names. I don't have better idea for now.

**Comment by sDos280** [comment]
👍, feel free to add any changes to the repository. because as I see it you are much better at knowing how stuff works in python...

**Pull request merged**
